/* eslint-disable import/no-anonymous-default-export */
export default {
  sports: [
    {
      id: "40",
      uid: "s:40",
      name: "Basketball",
      slug: "basketball",
      leagues: [
        {
          id: "59",
          uid: "s:40~l:59",
          name: "Women's National Basketball Association",
          abbreviation: "WNBA",
          shortName: "WNBA",
          slug: "wnba",
          teams: [
            {
              team: {
                id: "20",
                uid: "s:40~l:59~t:20",
                slug: "atlanta-dream",
                abbreviation: "ATL",
                displayName: "Atlanta Dream",
                shortDisplayName: "Dream",
                name: "Dream",
                nickname: "Atlanta",
                location: "Atlanta",
                color: "e31837",
                alternateColor: "5091cc",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/atl.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/atl.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/atl/atlanta-dream",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/atl/atlanta-dream",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/atl/atlanta-dream",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/atl",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/atlanta-dream-tickets--sports-wnba/performer/15200?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "19",
                uid: "s:40~l:59~t:19",
                slug: "chicago-sky",
                abbreviation: "CHI",
                displayName: "Chicago Sky",
                shortDisplayName: "Sky",
                name: "Sky",
                nickname: "Chicago",
                location: "Chicago",
                color: "5091cd",
                alternateColor: "ffd520",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/chi.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/chi.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/chi/chicago-sky",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/chi/chicago-sky",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/chi/chicago-sky",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/chi",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/chicago-sky-tickets--sports-wnba/performer/9058?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "18",
                uid: "s:40~l:59~t:18",
                slug: "connecticut-sun",
                abbreviation: "CONN",
                displayName: "Connecticut Sun",
                shortDisplayName: "Sun",
                name: "Sun",
                nickname: "Connecticut",
                location: "Connecticut",
                color: "f05023",
                alternateColor: "0a2240",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/conn.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/conn.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/conn/connecticut-sun",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/conn/connecticut-sun",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/conn/connecticut-sun",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/conn",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/connecticut-sun-tickets--sports-wnba/performer/5522?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "3",
                uid: "s:40~l:59~t:3",
                slug: "dallas-wings",
                abbreviation: "DAL",
                displayName: "Dallas Wings",
                shortDisplayName: "Wings",
                name: "Wings",
                nickname: "Dallas",
                location: "Dallas",
                color: "002b5c",
                alternateColor: "c4d600",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/dal.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/dal.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/dal/dallas-wings",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/dal/dallas-wings",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/dal/dallas-wings",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/dal",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/dallas-wings-tickets--sports-wnba/performer/47704?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "5",
                uid: "s:40~l:59~t:5",
                slug: "indiana-fever",
                abbreviation: "IND",
                displayName: "Indiana Fever",
                shortDisplayName: "Fever",
                name: "Fever",
                nickname: "Indiana",
                location: "Indiana",
                color: "002d62",
                alternateColor: "e03a3e",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/ind.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/ind.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/ind/indiana-fever",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/ind/indiana-fever",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/ind/indiana-fever",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/ind",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/indiana-fever-tickets--sports-wnba/performer/2016?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "17",
                uid: "s:40~l:59~t:17",
                slug: "las-vegas-aces",
                abbreviation: "LV",
                displayName: "Las Vegas Aces",
                shortDisplayName: "Aces",
                name: "Aces",
                nickname: "Las Vegas",
                location: "Las Vegas",
                color: "ce1141",
                alternateColor: "b4975a",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/lv.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/lv.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/lv/las-vegas-aces",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/lv/las-vegas-aces",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/lv/las-vegas-aces",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/lv",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/las-vegas-aces-tickets--sports-wnba/performer/75223?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "6",
                uid: "s:40~l:59~t:6",
                slug: "los-angeles-sparks",
                abbreviation: "LA",
                displayName: "Los Angeles Sparks",
                shortDisplayName: "Sparks",
                name: "Sparks",
                nickname: "Los Angeles",
                location: "Los Angeles",
                color: "552583",
                alternateColor: "fdb927",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/la.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/la.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/la/los-angeles-sparks",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/la/los-angeles-sparks",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/la/los-angeles-sparks",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/la",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/los-angeles-sparks-tickets--sports-wnba/performer/484?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "8",
                uid: "s:40~l:59~t:8",
                slug: "minnesota-lynx",
                abbreviation: "MIN",
                displayName: "Minnesota Lynx",
                shortDisplayName: "Lynx",
                name: "Lynx",
                nickname: "Minnesota",
                location: "Minnesota",
                color: "266092",
                alternateColor: "79bc43",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/min.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/min.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/min/minnesota-lynx",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/min/minnesota-lynx",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/min/minnesota-lynx",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/min",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/minnesota-lynx-tickets--sports-wnba/performer/1772?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "9",
                uid: "s:40~l:59~t:9",
                slug: "new-york-liberty",
                abbreviation: "NY",
                displayName: "New York Liberty",
                shortDisplayName: "Liberty",
                name: "Liberty",
                nickname: "New York",
                location: "New York",
                color: "86cebc",
                alternateColor: "000000",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/ny.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/ny.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/ny/new-york-liberty",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/ny/new-york-liberty",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/ny/new-york-liberty",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/ny",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/new-york-liberty-tickets--sports-wnba/performer/603?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "11",
                uid: "s:40~l:59~t:11",
                slug: "phoenix-mercury",
                abbreviation: "PHX",
                displayName: "Phoenix Mercury",
                shortDisplayName: "Mercury",
                name: "Mercury",
                nickname: "Phoenix",
                location: "Phoenix",
                color: "3c286e",
                alternateColor: "e56020",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/phx.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/phx.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/phx/phoenix-mercury",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/phx/phoenix-mercury",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/phx/phoenix-mercury",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/phx",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/phoenix-mercury-tickets--sports-wnba/performer/678?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "14",
                uid: "s:40~l:59~t:14",
                slug: "seattle-storm",
                abbreviation: "SEA",
                displayName: "Seattle Storm",
                shortDisplayName: "Storm",
                name: "Storm",
                nickname: "Seattle",
                location: "Seattle",
                color: "2c5235",
                alternateColor: "fee11a",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/sea.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/sea.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/scoreboard/sea.png",
                    alt: "",
                    rel: ["full", "scoreboard"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/scoreboard/sea.png",
                    alt: "",
                    rel: ["full", "scoreboard", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/sea/seattle-storm",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/sea/seattle-storm",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/sea/seattle-storm",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/sea",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/seattle-storm-tickets--sports-wnba/performer/1699?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
            {
              team: {
                id: "16",
                uid: "s:40~l:59~t:16",
                slug: "washington-mystics",
                abbreviation: "WSH",
                displayName: "Washington Mystics",
                shortDisplayName: "Mystics",
                name: "Mystics",
                nickname: "Washington",
                location: "Washington",
                color: "e03a3e",
                alternateColor: "002b5c",
                isActive: true,
                isAllStar: false,
                logos: [
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500/wsh.png",
                    alt: "",
                    rel: ["full", "default"],
                    width: 500,
                    height: 500,
                  },
                  {
                    href: "https://a.espncdn.com/i/teamlogos/wnba/500-dark/wsh.png",
                    alt: "",
                    rel: ["full", "dark"],
                    width: 500,
                    height: 500,
                  },
                ],
                links: [
                  {
                    language: "en-US",
                    rel: ["clubhouse", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/_/name/wsh/washington-mystics",
                    text: "Clubhouse",
                    shortText: "Clubhouse",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["roster", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/roster/_/name/wsh/washington-mystics",
                    text: "Roster",
                    shortText: "Roster",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["stats", "desktop", "team"],
                    href: "http://www.espn.com/wnba/team/stats/_/name/wsh/washington-mystics",
                    text: "Statistics",
                    shortText: "Statistics",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["schedule", "desktop", "team"],
                    href: "https://www.espn.com/wnba/team/schedule/_/name/wsh",
                    text: "Schedule",
                    shortText: "Schedule",
                    isExternal: false,
                    isPremium: false,
                    isHidden: false,
                  },
                  {
                    language: "en-US",
                    rel: ["tickets", "desktop", "team"],
                    href: "https://www.vividseats.com/washington-mystics-tickets--sports-wnba/performer/1770?wsUser=717",
                    text: "Tickets",
                    shortText: "Tickets",
                    isExternal: true,
                    isPremium: false,
                    isHidden: false,
                  },
                ],
              },
            },
          ],
          year: 2023,
          season: { year: 2023, displayName: "2023" },
        },
      ],
    },
  ],
};
